### ISSUE TITLE
401 error while clicking on any job post

### ISSUE THREAD

**Issue by ktaa13** [ivangfr/okta-springboot-react#1]
I am getting a 401 HTTP error when i click any job post or any other link. 

I logged in via OKTA successfully, but any other click on all links results in a 401

![image](https://user-images.githubusercontent.com/64479001/132026592-a734062d-0fc6-472d-958b-216bafe65879.png)

**Comment by ivangfr** [comment]
Hi @ktaa13!

I've cloned and followed the steps described in the README and it's working for me, as we can see in the GIF below

![jobs-portal-demo](https://user-images.githubusercontent.com/10564548/132056695-0fb43841-609c-4d9b-a728-f6c0a6e36d08.gif)

Maybe, you have missed some step.

Try to open the `Inspect` in the browser and go to `Application`. Then, find `Local Storage` > `http://localhost:3000` as shown in the picture below.

<img width="596" alt="Screen Shot 2021-09-03 at 20 40 50" src="https://user-images.githubusercontent.com/10564548/132058059-f56b6fd2-769a-493a-aa14-7d3c2759a355.png">

Check if you have values for `idToken` and `accessToken`.

If you have the `accessToken`, copy its value and go to https://jwt.io/

Paste the code there. Check if you have the `JOBS_STAFF` or `JOBS_CUSTOMER` group there as shown in the picture below

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/10564548/132057752-2a9585a8-6bc8-4e89-90b8-6304217f712b.png">

Let me know your findings.

**Comment by ktaa13** [comment]
![image](https://user-images.githubusercontent.com/64479001/132097823-eebcf31d-0257-4b41-b00d-4d1ca7a5d00c.png)


It seems that the group isnt being added to the jwt token although the user has it in okta admin dashboard

**Comment by ivangfr** [comment]
Looks like some missing configuration in **Okta**. Make sure you have followed the steps in README, mainly this one https://github.com/ivangfr/okta-springboot-react#assign-groups-to-application.

**Comment by lefperuch** [comment]
Hello there.

I decided to try this project and the same problem happened to me. The way I got around this was by following [this guide](https://developer.okta.com/docs/guides/customize-tokens-returned-from-okta/add-custom-claim/), more specifically I added one claim.

1. Go to Security > API
2. On the Authorization Servers tab, select either `default` or whatever the server that you're using
3. Claims > Add Claim

```
For Access Token: groups: matches regex .*
```

Then I can see the groups in my Token

```
{
  "ver": 1,
  "jti": "AT.kGXBS8lJ71jmgduf58ljuOMkPwU19QMdFcUqo1aBfQc",
  "iss": "<iss>",
  "aud": "api://default",
  "iat": 1633051155,
  "exp": 1633054755,
  "cid": "0oa22grgxbLJ7tEvK5d7",
  "uid": "00u22gs9e7KJPUiK35d7",
  "scp": [
    "openid",
    "profile",
    "email"
  ],
  "sub": "mario.bros@jobs.com",
  "groups": [
    "Everyone",
    "JOBS_STAFF"
  ]
}
```

**Comment by ivangfr** [comment]
Thanks @lefperuch for checking it out.

Indeed, I have those values in my Okta. Maybe, it's the key missing in my README in order to make it run smoothly.

I will update (as soon as possible) the README by adding the Security / API instructions.

@ktaa13 could you please try the steps suggested by @lefperuch 

Best regards and sorry for the mistake!

**Comment by ktaa13** [comment]
Dear @ivangfr 7 @lefperuch 

Yes indeed it worked after I did the mentioned workaround. Thank you for your support!
